# Use OpenJDK base image
FROM openjdk:17-jdk-slim

# Set the working directory
WORKDIR /app

# Copy all files into the container
COPY . .

# Build the project (optional if you push built .jar)
RUN ./mvnw clean package -DskipTests

# Run the application
CMD ["java", "-jar", "target/uams.jar"]
